# Generated by Django 4.2.6 on 2024-03-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('roll_number', models.IntegerField()),
                ('owner_email', models.CharField(max_length=50)),
                ('access_code', models.CharField(max_length=50)),
            ],
        ),
    ]
