# Generated by Django 4.2.6 on 2024-03-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('discount', models.IntegerField()),
                ('availability', models.CharField(max_length=50)),
            ],
        ),
    ]
